# Generated by Django 5.0.3 on 2024-03-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="interest_rate",
            new_name="rate",
        ),
        migrations.RenameField(
            model_name="loan",
            old_name="nominal_value",
            new_name="value",
        ),
        migrations.AddField(
            model_name="loan",
            name="contracted_period",
            field=models.PositiveSmallIntegerField(default=6),
            preserve_default=False,
        ),
    ]
