# Generated by Django 5.0.3 on 2024-03-15 20:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="nominal_value",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="Modificado em")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name="payments", to="core.loan"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
