# Generated by Django 5.0.3 on 2024-03-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_loan_request_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(default="2024-01-01"),
            preserve_default=False,
        ),
    ]
